name: new workflow_dispatch

on:
  workflow_dispatch:
jobs:
  pull-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: new_Pull data from Google Sheets
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python pull_data.py

      - name: Commit and push output.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add new_output.csv
          git diff --cached --quiet || git commit -m "test yml new_output.csv [automated]"
          git push
